export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';


export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';


export const PRODUCTS_FETCH_REQUEST = 'USER_SIGNUP_REQUEST';
export const PRODUCTS_FETCH_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const PRODUCTS_FETCH_FAIL = 'USER_SIGNUP_FAIL';


export const RECENT_PRODUCTS_FETCH_REQUEST = 'RECENT_PRODUCTS_FETCH_REQUEST';
export const RECENT_PRODUCTS_FETCH_SUCCESS = 'RECENT_PRODUCTS_FETCH_SUCCESS';
export const RECENT_PRODUCTS_FETCH_FAIL = 'RECENT_PRODUCTS_FETCH_FAIL';

export const PRODUCT_REVIEWS_FETCH_REQUEST = 'PRODUCT_REVIEWS_FETCH_REQUEST';
export const PRODUCT_REVIEWS_FETCH_SUCCESS = 'PRODUCT_REVIEWS_FETCH_SUCCESS';
export const PRODUCT_REVIEWS_FETCH_FAIL = 'PRODUCT_REVIEWS_FETCH_FAIL';
